package com.b2w.planetapi.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;
import java.util.Objects;

@DynamoDBTable(tableName = "planet")
public class Planet implements Serializable {

    @DynamoDBHashKey (attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String nome;
    @DynamoDBAttribute
    private String clima;
    @DynamoDBAttribute
    private String terreno;

    @DynamoDBAttribute
    private int aparicoes;

    public Planet(){

    }

    public Planet(String id, String nome, String clima, String terreno,int aparicoes ){
        this.id = id;
        this.nome = nome;
        this.clima = clima;
        this.aparicoes = aparicoes;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getClima() {
        return clima;
    }

    public void setClima(String clima) {
        this.clima = clima;
    }

    public String getTerreno() {
        return terreno;
    }

    public void setTerreno(String terreno) {
        this.terreno = terreno;
    }

    public int getAparicoes() {
        return aparicoes;
    }

    public void setAparicoes(int aparicoes) {
        this.aparicoes = aparicoes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Planet planet = (Planet) o;
        return id.equals(planet.id) && Objects.equals(nome, planet.nome) && Objects.equals(clima, planet.clima) && Objects.equals(terreno, planet.terreno);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, nome, clima, terreno);
    }
}
